---
# tasks file for python
#  - name: Install Python Dependencies
#    apt:
#      name: "{{ item }}"
#      state: present
#    with_items:
#      - python
#      - python-setuptools
#      - python-dev
#      - build-essential
#      - python-pip
#      - python-mysqldb

  - name: Install Python3 Dependencies
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - python3
      - python3-setuptools
      - python3-dev
      - build-essential
      - python3-pip
      - python3-mysqldb